import type { Metadata } from 'next'
import './globals.css'
import NavbarComp from '@/components/NavbarComp'
import FooterComp from '@/components/FooterComp'


export const metadata: Metadata = {
  title: 'Velocity Click',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

        {/* <!-- Standard favicon --> */}
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />

        {/* <!-- Apple Touch Icon (at least 200x200px) --> */}
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon.png" />

        {/* <!-- Android Chrome Icon --> */}
        <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="384x384" href="/android-chrome-384x384.png" />

        {/* <!-- Recommended favicon size for general browser display --> */}
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />

        {/* <!-- The Web App Manifest --> */}
        <link rel="manifest" href="/site.webmanifest" />

        {/* <!-- Safari Icon --> */}
        {/* <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"> */}

      </head>
      <body>
        <NavbarComp />
        {children}
        <FooterComp />
      </body>
    </html>
  )
}
