import type { Metadata } from 'next'
import './globals.css'
import { NextUIProvider } from '@/app/NextImport'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </main>
      </body>
    </html>
  )
}
